arb-dir: assets/translation
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: EssLocalizations
nullable-getter: false
use-deferred-loading: true
synthetic-package: false
output-dir: lib/src/common
