name: ess
version: 1.0.0+1
description: ESS two-factor authentication Linux module in Rust for the Manning Live Project.
homepage: https://helpisdev.github.io/ess
repository: https://github.com/helpisdev/ess-manning-rust.git
documentation: https://helpisdev.github.io/ess/docs
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  accessibility_tools:
  app_links:
  auth_buttons:
  autoequal:
  collection:
  cupertino_icons:
  dart_json_mapper:
  dart_json_mapper_fixnum:
  dart_json_mapper_flutter:
  dio:
  equatable:
  fixnum:
  flex_color_scheme:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  flutter_svg:
  flutter_web_plugins:
    sdk: flutter
  go_router:
  google_fonts:
  handy_window:
  intl:
  json_api:
  lottie:
  oxidized:
  path_provider:
  phone_form_field:
  platform:
  pretty_string:
  rive:
  riverpod_annotation:
  shared_preferences:
  state_notifier:
  stylesystem:
    path: packages/features/stylesystem
  supabase:
  supabase_flutter:
  universal_io:
  upgrader:
  url_launcher:
  uuid:

dev_dependencies:
  alchemist:
  autoequal_gen:
  bdd_widget_test:
  build_runner:
  build_test:
  build_web_compilers:
  checked_yaml:
  flutter_driver:
    sdk: flutter
  flutter_flavorizr:
  flutter_gen_runner:
  flutter_goldens:
    sdk: flutter
  flutter_test:
    sdk: flutter
  go_router_builder:
  icons_launcher:
  integration_test:
    sdk: flutter
  mocktail:
  riverpod_generator:
  spec:
  test:

dependency_overrides:
  collection: ^1.17.0
  xml: ^6.2.2

issueTracker: https://github.com/helpisdev/ess-manning-rust.git/issues

scripts:
  flavors: flutter pub run flutter_flavorizr
  regenerate_goldens: flutter test --update-goldens --tags=golden
  gen:build:prepare: 'flutter clean && flutter packages pub get'
  gen:build: flutter pub run build_runner build --delete-conflicting-outputs
  gen:build:post: flutter pub get
  gen:build:complete: 'derry gen:build:prepare && derry gen:build && derry gen:build:post'
  gen:watch: flutter pub run build_runner watch --delete-conflicting-outputs
  git:push: git push --recurse-submodules=on-demand --follow-tags
  git:pull: git pull origin main
  git:submodule:push: git submodule foreach 'git push'
  git:submodule:pull: git submodule update --remote --rebase
  git:submodule:checkout: git submodule foreach 'git checkout -b main'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/image/
    - assets/image/vector/
    - assets/image/raster/
    - assets/multimedia/
    - assets/multimedia/audio/
    - assets/multimedia/video/
    - assets/pdf/
    - assets/font/
    - assets/color/
    - assets/txt/
    - assets/animation/
    - assets/animation/rive/
    - assets/animation/lottie/

flavorizr:
  ide: vscode
  instructions:
    - assets:download
    - assets:extract
    - assets:clean
    - android:buildGradle
    - android:androidManifest
    - android:icons
    - ios:icons
    - ios:plist
  app:
    android:
      flavorDimensions: flavor-type
    ios:
  flavors:
    development:
      app:
        name: development
      android:
        applicationId: dev.helpis.ess
      ios:
        bundleId: dev.helpis.ess
    production:
      app:
        name: production
      android:
        applicationId: dev.helpis.ess
      ios:
        bundleId: dev.helpis.ess
    staging:
      app:
        name: staging
      android:
        applicationId: dev.helpis.ess
      ios:
        bundleId: dev.helpis.ess

flutter_gen:
  output: lib/src/common/
  line_length: 80
  gen_for_package: true
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
